volumes:
  prometheus_data: {}
services:
  bridge:
    image: onemorebsmith/kaspa_bridge:latest
    container_name: ks_bridge
    restart: unless-stopped
    user: "0"
    command:
      - '-log=false'
      - '-stats=false'
      - '-stratum=":5555"'
      - '-prom=":2112"'
      - '-kaspa="localhost:16110"'
    ports:
      - 5555:5555
      - 2112:2112
  grafana:
    image: grafana/grafana-oss:latest
    container_name: ks_grafana
    restart: unless-stopped
    user: "0"
    volumes:
      - ./docker/grafana:/var/lib/grafana
    env_file:
      - ./docker/grafana.env
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway
  prometheus:
    image: prom/prometheus:latest
    container_name: ks_prom
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--docker.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal:host-gateway
